# Menus
menu:
  #Home: .
  Archives: archives
  #Categories: categories
  #Tags: tags
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/twelve.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: https://avatars3.githubusercontent.com/u/4124275?v=3&u=f586395eafd04b466570ac27ffe036862dbae0d6&s=140
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: 오도연
        author_title: Web Developer
        location: Seoul, Korea
        follow: https://github.com/doyeonOh
    # highlight: arta
    sidebar: left # sidebar position, options: left, right
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: css/images/favicon.ico# path to favicon
    social_links:
        github: https://github.com/doyeonOh
        #twitter: /        facebook: /
        #dribbble: /
        facebook: https://www.facebook.com/odyody12
        rss: /feed.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - category
    - recent_posts
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: doyeonoh
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true
    google_analytics: UA-84397130-1
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins: 100000731937646
        twitter_id:
        google_plus: odyody12@gmail.com
    links:
        #Hexo: http://hexo.io
